{******************************************************************************}
{ Projeto: AG ORM                                                    }
{  Biblioteca multiplataforma de componentes Delphi para interação com equipa- }
{ mentos de Automação Comercial utilizados no Brasil                           }
{                                                                              }
{ Direitos Autorais Reservados (c) 2018 Anderson Gaitolini               }
{                                                                              }
{                                                                              }
{  Esta biblioteca é software livre; você pode redistribuí-la e/ou modificá-la }
{ sob os termos da Licença Pública Geral Menor do GNU conforme publicada pela  }
{ Free Software Foundation; tanto a versão 2.1 da Licença, ou (a seu critério) }
{ qualquer versão posterior.                                                   }
{                                                                              }
{  Esta biblioteca é distribuída na expectativa de que seja útil, porém, SEM   }
{ NENHUMA GARANTIA; nem mesmo a garantia implícita de COMERCIABILIDADE OU      }
{ ADEQUAÇÃO A UMA FINALIDADE ESPECÍFICA. Consulte a Licença Pública Geral Menor}
{ do GNU para mais detalhes. (Arquivo LICENÇA.TXT ou LICENSE.TXT)              }
{                                                                              }
{  Você deve ter recebido uma cópia da Licença Pública Geral Menor do GNU junto}
{ com esta biblioteca; se não, escreva para a Free Software Foundation, Inc.,  }
{ no endereço 59 Temple Street, Suite 330, Boston, MA 02111-1307 USA.          }
{ Você também pode obter uma copia da licença em:                              }
{ http://www.opensource.org/licenses/gpl-license.php                           }
{                                                                              }
{ Anderson Gaitolini -  gaitolini@gmail.com               }
{                                                                              }
{******************************************************************************}

{******************************************************************************
|* Historico
|*
|* 14/09/2018: Primeira Versao
|*    Anderson Gaitolini
|*    Criaçao e Distribuiçao da Primeira Versao

******************************************************************************}

// Descomente as linhas abaixo para usar os recursos desejados
//--------------------------------------------------------------------------------
{$DEFINE FMX}
{$DEFINE VCL}

{$DEFINE FIREBIRD}
{.$DEFINE MYSQL}

{.$DEFINE ZEOSLIB}
{$DEFINE FIREDAC}
{.$DEFINE FIBPLUS}


